apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-73-ocp48-cnf"
  namespace: "master-73-ocp48-cnf"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.8.22-x86-64-appsub" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBoC8xDDJF0mmO7hrZw/yReEnm44/fHyJxTET1ooWzjjwAbEX7awns1W6FN15Hbu8Lf6ajiVR9OrMJXRJpV5ip+lG2Ub6MVpGqONSSCRR34v+d36/CKYBf13L8nsNukQZ1Q6ONLlmmbu/rEuolxwV6Xcm4Yhyrbrlz81xEj5yOH2472S30+oTwevE1bS2s8Gi8DOXBckcv6s0vylMhNgOMhiKabgD02jDIuMhIQjkspwyYLmW2EHXN/rulpSQkdr1t6DnVsi9eSb0rA3Ac7CZlrmtcZd0Gd/rEx83q4XU6a7/i/RajG0eSDj1h0iMss3kxh6YARsSxXAk4RMbBOsqn"
  clusters:
  - clusterName: "master-73-ocp48-cnf"
    clusterType: "sno"
    clusterProfile: "cu"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-73-ocp48-cnf"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-73-ocp48-cnf"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.73/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-73-ocp48-cnf-master-73-ocp48-cnf-bmh-secret"
         bootMACAddress: "78:AC:44:32:7A:D0"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "78:AC:44:32:7A:D0"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "78:AC:44:32:7A:D0"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
