apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-84-sno"
  namespace: "master-dell-84-sno"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.9.9-master-4-ocp49-2" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2JyAz+qRgTZQFSg6KZG325LakxZRmTbm4Ma51lq3TG6ws7qfwRg3pe3I1Zgezj2WKrCoB7DL2P3SnO+9Uu1t9ayKUwfCm0KN6UIQ9o6H9tB03/m/CmGVAborfTN6Z3pUYxp9Hcla7/cjTzRcLNNAJ9cG1dE77xKBgYXCY4I0sEoS5aC7Wca5X7IiP1h5yNvSlttANfbsX1DKlVLVqwRcKwg2PeWmH7V9vJ+h+SF96/Y0TzqNPQtKT/lvloA9yhPytBotzBW29eVA1uF83meAtb3Ervj0d0KDyHdu9jEVQ/CapoMmxEhmBsztIUxEnNw5W822804Z1dMpMd/FkCl83"
  clusters:
  - clusterName: "master-dell-84-sno"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-84-sno"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-84-sno"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.84/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-dell-84-sno-master-dell-84-sno-bmh-secret"
         bootMACAddress: "E4:43:4B:F1:02:40"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F1:02:40"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F1:02:40"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
