---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./cu01-test  

resources:
  - 40-vcu-cluster-bangalore-dell-cu.yaml  
  - 50-vcu-cluster-bangalore-dell-cu-00-pre.yaml
  - 60-vcu-cluster-bangalore-dell-cu-01-post.yaml  
  - 70-vcu-cluster-bangalore-dell-cu-02-virtualization-configs.yaml
  - 80-vcu-cluster-bangalore-dell-cu-02-settings.yaml
