apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno-qa-cluster"
  namespace: "sno-qa-cluster"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.8.18"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZA9BIFmQ/FwR1Id+6tMzolcIYbiPFudrSEL37mZkgcngk6qJw0VHMRor4hYjJt8mEAA10F8I7/ZYpFE+70WWm94jPZ8Co/8QGANbPtGlEaCAhma9VdpseM4/sVUYtYGs9FuwdRWNE9xCYf2jd25COZsEKUU/6tko/tGO7Xx4v0Rm5/e4iK/yoTZjMMXIu92rkJzIAytQfmv08Tc13dZI0M2CRj/cYbVYgRAwhalDJyo/2gbydrTrTuF6OiU3tRog57ARDEc7h3PkVt/rxTgH+JmS3Nyg+Yg+BYk2vSmErClU6kmYSmcDbvbBM/6L3k2QoqFxo8Tbquw083/7l2QlV"
  clusters:
  - clusterName: "sno-qa-cluster"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "sno-qa-cluster"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-9-ocp48.sno-qa-cluster.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.102/redfish/v1/Systems/System.Embedded.1"
         bmcCredentialsName:
           name: "sno-qa-cluster-master-9-ocp48-bmh-secret"
         bootMACAddress: "3C:EC:EF:5E:3C:4C"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "3C:EC:EF:5E:3C:4C"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "3C:EC:EF:5E:3C:4C"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
