apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-39-qa-cb100"
  namespace: "master-dell-39-qa-cb100"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.8.18"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeUpul1WauxUZXinahjr5PMBi0cvMLH3ZqxQ0BfomQ02GJV0ReSaThaHTBdQs+1yw7/ktbfXvOngvle/5AM+UMRJBZCtgeo3feFv7NajPbTg4o8qh/xt4k/bvqSknkQBz83/fVLxhuKqclT3txqJ9S6vPupGnlVdcWrzWYnxgP3PtN/YGGn/mpywhnIXuQ+kmvFmRHe88jahAer1eAg6QcCC6FxOUZLthqNQKYcHA1ocAAu/Gx3ALkEwkoB2DS1DQwa2faNIFoPapmxFObY8PV3h/KHz/DKDiuiJnRTlfEcUECBeItlVpgJBopoBFF80H6vYVeoBIsBI8bj6RwDCbX"
  clusters:
  - clusterName: "master-dell-39-qa-cb100"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-39-qa-cb100"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-39-qa-cb100.master-dell-39-qa-cb100.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.39/redfish/v1/Systems/System.Embedded.1"
         bmcCredentialsName:
           name: "master-dell-39-qa-cb100-master-dell-39-qa-cb100-bmh-secret"
         bootMACAddress: "F0:D4:E2:E8:BE:94"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "F0:D4:E2:E8:BE:94"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "F0:D4:E2:E8:BE:94"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
