---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: delhi-local-storage-server-profile-du-dell00
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: ran.openshift.io/delhi-local-storage-server-profile-du-dell00
          operator: Exists
  storageClassDevices:
    - storageClassName: "delhi-local-storage-server-profile-du-dell00"
      volumeMode: Filesystem
      fsType: xfs
      # Update to match profile composition
      devicePaths:
        #- /dev/nvme1n1p4
        # - /dev/nvme1n2