apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-42-jan"
  namespace: "master-dell-42-jan"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.9.9-master-4-ocp49-2" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGNW0WE2WSbVUM0btgdhy5LbuRk1PQ81v1SN5J91133SgheZ5ZjZ05km/3Nko4nyF3D0lm0dxLdC9lo3toKaMPGLVH3Q0z60ojJ9OYWg3Hhzn6JsOJOLvuitZ3jU/+091zFJa5dp5fUXd2YqtiDzTu3888nmRDQTsKS0klHEVe4sAIw7iWrop8mYao0tiSr/Ofps7vcUHIsM45y6mr1Td1ALQ/K95XnI7hAD+Nkop2Zj30xcDknJppTrn+DHrEotAZmfYVrVxVQiNQzXnHXUM7uAG+wcdfzvIysQIVKDTpAGAQt9jqlsdqJWrJW+8KQn/oL5fZ+2Mcgi6qnsDtxYb3"
  clusters:
  - clusterName: "master-dell-42-jan"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-42-jan"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-42-jan"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.42/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-dell-42-jan-master-dell-42-jan-bmh-secret"
         bootMACAddress: "F0:D4:E2:E8:E9:2C"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "F0:D4:E2:E8:E9:2C"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "F0:D4:E2:E8:E9:2C"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
