apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-42-jan"
  namespace: "master-dell-42-jan"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.9.9-master-4-ocp49-2" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDS7CTjeH7RNQSfW52ZWZ5r5WvQMr2mc8AiFGHp1JzYspc03mDtlMOvPy3OUqYKgAMJwvlIm2UAX88PuyLCQERW6wrUVUttlKu9HzkocnDKQd9LqXYJ0T9FK5jKrAweH9bQ5X6Q1APFcQ203pbiSJBcCb2jKB6umbAADrelR7A57AJnOM6B3+OgXXtsB2JsLJu1W0fTetN1pOv52IkGKjKaKUkkpTrbeEBambYDtU68fA0qU2mjIqz/lWG6jeZ0J+XMOD1hD2QGgMdDmQ99ytedvLpjf55poF8CtJxDCqiw9ZmIkUNjkPy9U0JrcmH9kKMFibaYT9wRGzflgSXu4E81"
  clusters:
  - clusterName: "master-dell-42-jan"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-42-jan"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-42-jan"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.42/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-dell-42-jan-master-dell-42-jan-bmh-secret"
         bootMACAddress: "F0:D4:E2:E8:E9:2C"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "F0:D4:E2:E8:E9:2C"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "F0:D4:E2:E8:E9:2C"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
