apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-44-qa16"
  namespace: "master-dell-44-qa16"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.8.18-x86-64-appsub" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCorgPEmGT0vzUfjJW6n0H6pA24wqUYYeV4DOuYkBUWvb8shqhNiq9Jpt+X5ShXnOOlVtJ2L1u93qzVQ8JduJ7PZxLAWghWenJk9pnZAcIQ6ssD3WrRPWrviJrbVsmqKf8nsoeBCZEXWav6U4HQYQ21orYDa0VE3xVFA0odOvRBb80TSwnKvjGi3i2n/c3NVKq+uzxFRBw3yOPrHjyrYoEdPk9X+dDkZ+k95f7xGtNkKvgA5VBLBMlDjao5HoCoODCIWYruEmjg4hF2lsXnvI7mZF7FmRRquz4BI8mDOilzE9bou3XWbQHFTZjG2tD4WPDEtapEkjw2Pq+bJYLmzEg9"
  clusters:
  - clusterName: "master-dell-44-qa16"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-44-qa16"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-44-qa16"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.44/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-dell-44-qa16-master-dell-44-qa16-bmh-secret"
         bootMACAddress: "78:AC:44:22:9B:74"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "78:AC:44:22:9B:74"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "78:AC:44:22:9B:74"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
