apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-44-qa16"
  namespace: "master-dell-44-qa16"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-4.8.18" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3H1mHklGqUWEp6atfbsNB65Bz4rD4qZgRA4nZyujXTyFVqp8j41VioUXH2ar8Bl+fSgE42Ase69WGJTLqZ8xFBMpfpLHkQZUWe/+3+RdvpFSy4Mw+zhy0TzaOCZB6YA2x01uzfkGbR34OXvI6BK4qEpgBfUQL6WhE4ORDdITJFru9XOkq6ZnNYWFWCxABbAk79Np9FusaxwgDMzkz+zDzqqtjKEbtXNCsjGbYnqXMUdiia9/WvuK/HXmglAL8jVOoOBvkf6L3Be48kLUi4djNwoe162mVTISH7Pys5CiGco1P4lEq5GppvzfVGKjCSdoGCK6EaPdmmSjbUzj6i/TP"
  clusters:
  - clusterName: "master-dell-44-qa16"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-44-qa16"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-44-qa16"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.44/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-dell-44-qa16-master-dell-44-qa16-bmh-secret"
         bootMACAddress: "78:AC:44:22:9B:74"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "78:AC:44:22:9B:74"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "78:AC:44:22:9B:74"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
