apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-44-qa3"
  namespace: "master-dell-44-qa3"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.8.18"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+hGzO/UPgbJ0FnnSqzUoFf1ToBiEx6qlzyUaoyaHlVY5h11Xf5XZSwfBuBHzlg/j3Obv/JmiOl4T1Ga1ce3E/MfpoPHXQ3duJ75nOoWWJz7J62VNRwww5kcB4Gz7BeXiGt/g711TIrwd4jay96UYcksHF7PB8xST+59H4Wxp1GVQJZHPm61dv0Oxqo8JH05TswPsPI5KVyGAKshfbnSwiSkDl0rlHeCNImNzxIQkQfKwVsuLmiKUpG0FqJp2yF10dd6L8McKI4mqFHXBsNgjiScv5BD8W8IpHRYxsiSmBB5W4B3WwnK4TEAfVDQ8nLH4S0LilDDoLI6jppwp16jSj"
  clusters:
  - clusterName: "master-dell-44-qa3"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-44-qa3"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-44-qa3.master-dell-44-qa3.vran.ibm.com"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.44/redfish/v1/Systems/System.Embedded.1"
         bmcCredentialsName:
           name: "master-dell-44-qa3-master-dell-44-qa3-bmh-secret"
         bootMACAddress: "78:AC:44:22:9B:74"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "78:AC:44:22:9B:74"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "78:AC:44:22:9B:74"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
