 
---
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: bangalore-sriov-vfio-sb-dell00-server-profile-cu-dell-r640-00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio_sb"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/bangalore-sriov-vfio-server-profile-cu-dell-r640-00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 4
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens1f0#0-3


---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: bangalore-sriov-vfio-dell00-server-profile-cu-dell-r640-00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/bangalore-sriov-vfio-server-profile-cu-dell-r640-00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 64
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens1f0#4-11
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: bangalore-sriov-a-vfio-dell00-server-profile-cu-dell-r640-00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio_a"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/bangalore-sriov-vfio_a-server-profile-cu-dell-r640-00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 64
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens1f0#12-19
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: bangalore-sriov-vfio-b-dell00-server-profile-cu-dell-r640-00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio_b"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/bangalore-sriov-vfio_b-server-profile-cu-dell-r640-00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 64
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens1f0#20-27
    
