---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: phoenixqa1
  namespace: phoenixqa1
spec:
  baseDomain: vran.ibm.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: phoenixqa1
    version: v1beta1
  clusterName: phoenixqa1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: phoenixqa1
  pullSecretRef:
    name: assisted-deployment-pull-secret

---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: phoenixqa1
  namespace: phoenixqa1
spec:
  apiVIP: 9.37.195.53
  ingressVIP: 9.37.195.54
  clusterDeploymentRef:
    name: phoenixqa1
  #holdInstallation: true
  provisionRequirements:
    controlPlaneAgents: 3
  imageSetRef:
    name: "vran-ocp-v4.9.9-master-4-ocp49-2"
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZShVAFP7g/h6A6FDAg1cJsAFjUYPOTc1WOk52V3lSr/Ce8Lfp02e1M9kA5oSJ1NJh5xm74gXxJAOHZ0Gd+mBJcLdwiRiL+1VFaPPuLiUtvjXb9MPkU25c+L8PkDjhmnOKO+9be6quEb3458PNtor5Zgert51mT917RiPx0iZmlMwBl9mHBCDb/3rRxUhebaxxEdU2ydFUaLewL25K+cuUhHbefBFrQEYwjACPny76g6SGrUUeQhFgo4sVfEfmCmzpyM6YpJU83TFk1nYKga8gB+VrqdwwhyImIUkINKcgoZyZfbiTfq4+uvMNRwKDYcBV3GeWSgFdrelwGkAX7uov"

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: phoenixqa1
  namespace: phoenixqa1
spec:
  clusterName: phoenixqa1
  clusterNamespace: phoenixqa1
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true

---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: phoenixqa1
  namespace: phoenixqa1
  
spec:
  clusterRef:
    name: phoenixqa1
    namespace: phoenixqa1
  # agentLabelSelector:
  #   matchLabels:
  #     cluster-name: phoenixqa1
  pullSecretRef:
    name: assisted-deployment-pull-secret
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZShVAFP7g/h6A6FDAg1cJsAFjUYPOTc1WOk52V3lSr/Ce8Lfp02e1M9kA5oSJ1NJh5xm74gXxJAOHZ0Gd+mBJcLdwiRiL+1VFaPPuLiUtvjXb9MPkU25c+L8PkDjhmnOKO+9be6quEb3458PNtor5Zgert51mT917RiPx0iZmlMwBl9mHBCDb/3rRxUhebaxxEdU2ydFUaLewL25K+cuUhHbefBFrQEYwjACPny76g6SGrUUeQhFgo4sVfEfmCmzpyM6YpJU83TFk1nYKga8gB+VrqdwwhyImIUkINKcgoZyZfbiTfq4+uvMNRwKDYcBV3GeWSgFdrelwGkAX7uov"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-80-std"
  namespace: phoenixqa1
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa1"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.80/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa1-master-dell-80-std-bmh-secret
  bootMACAddress: E4:43:4B:F0:E3:00
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-81-std"
  namespace: phoenixqa1
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa1"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.81/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa1-master-dell-81-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:01:10
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-82-std"
  namespace: phoenixqa1
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa1"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.82/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa1-master-dell-82-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:A4:E0
  automatedCleaningMode: disabled
  online: true
---
