---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./cu-01  

resources:
  - 40-dev-cluster-vizag-dell-cu.yaml  
  - 50-dev-cluster-vizag-dell-cu-00-pre.yaml
  - 60-dev-cluster-vizag-dell-cu-01-post.yaml  
  - 70-dev-cluster-vizag-dell-cu-02-virtualization-configs.yaml
  - 80-dev-cluster-vizag-dell-cu-02-settings.yaml