apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-42-sno"
  namespace: "master-dell-42-sno"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.9.9-master-4-ocp49-2" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDK+or9gQItqqKnp7f7bNRjOw7MiCkvsFW4HXZ6i8Ug1AOhbqjSA192O/A+lJ/O/gN5xQ6F5xXP1q0o1rO1JL81UtoMs2ZChXmaO5SnHOrejDR7c1gUq/4hzgaPHSZJF/aQXL/vSfPBGe8GzpRBT7/hMjjMAxsyUC/T/0BTcIJwk5Fpew0zEY9N3JsyPYVQui1RjCHZEAHJiayZtL7L5zWbfR6+U0/y/4UMvr02D/0ygn6mRY3mpshg0wsAnpD4m/xODwa6YcIKgP7Ko8QI8cddRXQNbJwBP8numVQO6EKJMT4RVuRpLA1mI+emddlcz7Pery4yo4GFMz8NEWooulGv"
  clusters:
  - clusterName: "master-dell-42-sno"
    clusterType: "sno"
    clusterProfile: "cu"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-42-sno"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-42-sno"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.42/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-dell-42-sno-master-dell-42-sno-bmh-secret"
         bootMACAddress: "F0:D4:E2:E8:E9:2C"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "F0:D4:E2:E8:E9:2C"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "F0:D4:E2:E8:E9:2C"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
