---
apiVersion: v1
kind: Namespace
metadata:
  name: altiostar-4g-cu-vizag
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-pod2-certs-vizag-cu
  namespace: altiostar-4g-cu-vizag
  labels:
    app: containerized-data-importer
type: Opaque
data:
  accessKeyId: ZHVtbXk=
  secretKey:   ZHVtbXk=