apiVersion: v1
kind: ConfigMap
metadata:
  name: 4glte-du-2-mysore-p1
  namespace: altiostar-4g-du-mysore
data:
  prov.ini:   |
    panel-id: 44
    hostname: vrandu2-test.com
    serial-no: masa1w21e21dfq
    mgmt-intf: net1
    mh-intf: net2
    mp-intf: net3
    fh-intf: net4
    oran-support: True
    skip-sw-upgrade: True
    nw-type: v4
    ha-enabled: True
    ar-nw-enabled: False
    tim-pod-present: True
    device-type: RIU-D
    vcu-fqdn: vdu2.rma.lan.com
    mp-vlan-id: 2003 
    fh-vlan-id: 2001
    riu-vlan-id: 2001
    initial_rtd_check: False
