apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-43-jan13"
  namespace: "master-dell-43-jan13"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.8.22-master-sm-105-jan4" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCadhWS1q1Qi+ZGlgOc9/ShpF60HrgkKPA14WQy1aCVKeHHjzMFNG+RgdaB1zCwu8dwEi7no6rl2yfgWzOBiziHyJOhPU4r9HVHv220CByMguIrANr5qS4wqtSBVs9C667SdrgeaMqy3kYF0TfLZt7dxPyBsGP7dwxTN9T6FtYxZKDJtfj9b1EfnbzNlDWsbFiI6eLlER+dSzkqEsqQCXYJHK+HqPCaYr4BbPfqq5VjqpMtPb5VDwg0iWfVszFGqqn0O/xgEXLxTArebGWKLMpE/eaxYPqt/cNsUdaWaEINFf+prylI46b2rPRD+ets8jrPVx1RxFFGJFzlkXmpkHD"
  clusters:
  - clusterName: "master-dell-43-jan13"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-43-jan13"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-43-jan13"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.42/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-dell-43-jan13-master-dell-43-jan13-bmh-secret"
         bootMACAddress: "F0:D4:E2:E8:E9:2C"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "F0:D4:E2:E8:E9:2C"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "F0:D4:E2:E8:E9:2C"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
