apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-43-jan13"
  namespace: "master-dell-43-jan13"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.8.22-master-sm-105-jan4" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAtC9hDLe2HZQW5aUf9JZU8qFY5AZ849o87S/9Z1UjDwc8P3LA30CLMwzhTJIE14tmwPEjyJ3fW/TrHRKCx7JgYgFAeNwfepd86RZLfu+YKbr6FXaWcue+Vuejm2Z8ol8xNHctKRkUHcZe2UncR6xNWGH5AQJ7sbU9A1VMzTemiQTCXKcN9/SSdgkjTZCBXGVP5aRod/wE+kuZbA96eYTrW7X10qu2MzOTrqYjS+Ls1FE8RLPBxCFuyghgcIDE80OuAFCy3DyPKjwEkXHGqCK/vGnY+lQcvZzlasFeaH1Tw3I4xboZzAZUB7/1ffd/Y+BLf4e23ciSYOLzN+UJ4Fbj"
  clusters:
  - clusterName: "master-dell-43-jan13"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-43-jan13"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-43-jan13"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.42/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-dell-43-jan13-master-dell-43-jan13-bmh-secret"
         bootMACAddress: "F0:D4:E2:E8:E9:2C"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "F0:D4:E2:E8:E9:2C"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "F0:D4:E2:E8:E9:2C"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
