apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-43-jan13"
  namespace: "master-dell-43-jan13"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.8.22-master-sm-105-jan4" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC245FsIN3Zj0U4LfpfNeS46odRbGxU8St/eisLr0V1TBFuYFzG4HwHSSp45BurtlE9OhSUqxDxfhclrCqhB3tM9GpzcJH2mNp8m6gZsdZGv9zQ1HTjnRqjucoQcS1bd5tPWKarl3c6XD+wKtpDAPjh5WIk93OdiD36DlqhIuH6lpbFQyn7Q1VD12a/S+MTdgy90DIty3nDcW8MEpEeBslxR9ulN+0hPGs+645VEiybDPsXsoV2UGCB6EEBZO0RdELBtVZJpoyPOUT2iKBaIH55TWOpx6ZIsPg/xpBriqMBxyZqhaYw4A6WqGDE3amywmBs69sckXX5I4Qg35rjyKOz"
  clusters:
  - clusterName: "master-dell-43-jan13"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-43-jan13"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-43-jan13"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.42/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-dell-43-jan13-master-dell-43-jan13-bmh-secret"
         bootMACAddress: "F0:D4:E2:E8:E9:2C"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "F0:D4:E2:E8:E9:2C"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "F0:D4:E2:E8:E9:2C"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
