---
apiVersion: v1
kind: Namespace
metadata:
  name: altiostar-4g-cu-delhi
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-pod2-certs-delhi-cu
  namespace: altiostar-4g-cu-delhi
  labels:
    app: containerized-data-importer
type: Opaque
data:
  accessKeyId: "dnJhbmFkbWlu"
  secretKey: "cGFzc3dvcmQ="
  