apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-dell-82"
  namespace: "master-dell-82"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "vran-ocp-v4.9.9-master-4-ocp49-2" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0l66+YJhC7wKnT/So0w4pfRo51sMho7bQCb18nPL37AhNoOUO5KZoQgftoUvcvpoNMLHK56hTGkgNv8loff4xKgFi0TkvKJNHJ1ZMJPKCDcHrRjqn0r1we7bTa7S0xnSfsYqBuYPHYH51ir9dtszi0r3JX8TooyYbOPM9mQuFIJ4gMtv3k1bGI/Fx1VXV861ARemUW71g3OGHnc7hij0nk1oppBSTgpv83wzzxV3YVaZ6BYE7hqIovkMK65WUcoFAl3imA0ajuCKso9tc4RJcGtwZIxIDpN5Tc3zFeYb6kpH8yuKHjtTwxpRpQhItSt5Ltar9t+ZHsEkzZaMkWdlt"
  clusters:
  - clusterName: "master-dell-82"
    clusterType: "sno"
    clusterProfile: "cu"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-dell-82"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-dell-82"
         bmcAddress: "idrac-virtualmedia+https://9.37.131.82/redfish/v1/Systems/System.Embedded.1" 
         bmcCredentialsName:
           name: "master-dell-82-master-dell-82-bmh-secret"
         bootMACAddress: "E4:43:4B:F1:A4:E0"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sdb"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "E4:43:4B:F1:A4:E0"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "E4:43:4B:F1:A4:E0"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
