---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-du-mysore-server-profile-du-supermicro00

commonAnnotations:  
#  argocd.argoproj.io/sync-wave: "10"
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/compare-options: IgnoreExtraneous  

bases:
  - ./00-pre  
  - ./01-post
  - ./02-configs
#  - ./03-n3000/03-n3k
  - ./03-n3000/n3k-cluster
#  - ./03-n3000/n3k-sriov
  - ./03-n3000/sriovfec-clusterconfig    
  - ./04-timingmgr
  - ./du-01
  

resources:
  - 00-worker-2-du-labels-job.yaml

  - 00-wait-job-sa-role.yaml
  - 01-mcp-wait-job-sa-rolebinding.yaml