---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: cluster01
  namespace: cluster01
spec:
  baseDomain: vran.ibm.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: cluster01
    version: v1beta1
  clusterName: cluster01
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: cluster01
  pullSecretRef:
    name: assisted-deployment-pull-secret

---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: cluster01
  namespace: cluster01
spec:
  apiVIP: 9.37.195.12
  ingressVIP: 9.37.195.15
  clusterDeploymentRef:
    name: cluster01
  #holdInstallation: true
  provisionRequirements:
    controlPlaneAgents: 3
  imageSetRef:
    name: "vran-ocp-v4.9.9-cluster01"
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZqN7i+p3qsr7m3THuIh0L3oMJU2JIUbFwVxB0Zf9JfuGih/fCvAgULdDe+NYN0fFvXynD0F90g5GP8BIHN4MMJ8wbrVnR28mJvD3Eeg5QCWe9fVsKR6+dTwvbYiyjOG6XVzg30/9NWTJtPLLaJ8ADzBwawJDEX4wLaE0ldF8+8K3EfMXE9Y84jTetTEh4SH7+HGNzziqGMMBW7//jBEkmc82jzAXMbfGWW+OzyMAehEcqrVXcIGQvh+/XEIR+JMRwWRS0Vo+FLNP3CIg0qQ0aQLF5BdzpEkd76lqDyupENlSaWYypsZ2HAUtU318rws5LBpoVe0Lcd6ixGlYS1w/H"

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: cluster01
  namespace: cluster01
spec:
  clusterName: cluster01
  clusterNamespace: cluster01
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true

---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: cluster01
  namespace: cluster01
  
spec:
  clusterRef:
    name: cluster01
    namespace: cluster01
  # agentLabelSelector:
  #   matchLabels:
  #     cluster-name: cluster01
  pullSecretRef:
    name: assisted-deployment-pull-secret
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZqN7i+p3qsr7m3THuIh0L3oMJU2JIUbFwVxB0Zf9JfuGih/fCvAgULdDe+NYN0fFvXynD0F90g5GP8BIHN4MMJ8wbrVnR28mJvD3Eeg5QCWe9fVsKR6+dTwvbYiyjOG6XVzg30/9NWTJtPLLaJ8ADzBwawJDEX4wLaE0ldF8+8K3EfMXE9Y84jTetTEh4SH7+HGNzziqGMMBW7//jBEkmc82jzAXMbfGWW+OzyMAehEcqrVXcIGQvh+/XEIR+JMRwWRS0Vo+FLNP3CIg0qQ0aQLF5BdzpEkd76lqDyupENlSaWYypsZ2HAUtU318rws5LBpoVe0Lcd6ixGlYS1w/H"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-80"
  namespace: cluster01
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "cluster01"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.80/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: cluster01-master-dell-80-bmh-secret
  bootMACAddress: F4:02:70:F1:53:62
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-81"
  namespace: cluster01
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "cluster01"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.81/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: cluster01-master-dell-81-bmh-secret
  bootMACAddress: F4:02:70:F1:5C:4A
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-82"
  namespace: cluster01
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "cluster01"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.82/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: cluster01-master-dell-82-bmh-secret
  bootMACAddress: F4:02:70:F1:60:52
  automatedCleaningMode: disabled
  online: true
---
