apiVersion: v1
kind: ConfigMap
metadata:
  name: 4glte-du-2-bangalore-p1
  namespace: altiostar-4g-du-bangalore
data:
  prov.ini:   |
    panel-id: 44
    hostname: vrandu2-test.com
    serial-no: DUJ8JUNKA9H004
    mgmt-intf: net1
    mh-intf: net2
    mp-intf: net3
    fh-intf: net4
    oran-support: yes
    skip-sw-upgrade: yes
    nw-type: v4
    ha-enabled: yes
    ar-nw-enabled: no
    device-type: RIU-D
    vcu-fqdn: rhocp-vcu1.rma.lan
    mp-vlan-id: 2003 
    fh-vlan-id: 2001
    riu-vlan-id: 2001
    initial_rtd_check: no
