apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "master-sm-105-ocp48-qa17"
  namespace: "master-sm-105-ocp48-qa17"
spec:
  baseDomain: "vran.ibm.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.8.18-x86-64-appsub" 
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDw5Ogux6dl1SCQytUQk+kWcEaJgPxHKdHPb+B83oEdFaRKqE6k6DronIo/dwWZMrhdoYtxhYYqskjjv/Fwx4JVSqNpivKpQ8ToTkFQsNmEBnXfDV8gl5GwGN1gpP93Xoae6mqT3FiSFYAcNE0m3bjkSHgL30efTmYnCPN0yNenfr/znxuzJV4KdpuxSaC4+2al97j9GCd7DndIg/EDcEApH9hRDa29kPVx2ivcKhALnMhjVVHv+v9+0eyTqAobPZR6JMZbFKHBnzUIXlG/fsMT9HSS2mFAf4h1z8wb7W2Wx8zysDrH4GuSWaIetppRTt6uJfLLMW2hfNIZ1hs0/rtb"
  clusters:
  - clusterName: "master-sm-105-ocp48-qa17"
    clusterType: "sno"
    clusterProfile: "du"
    numMasters: 1
    clusterLabels:
      common: true
      sites : "master-sm-105-ocp48-qa17"
    clusterNetwork:
       - cidr: 10.128.0.0/14
         hostPrefix: 23
    serviceNetwork:
       - 172.30.0.0/16
    machineNetwork:
       - cidr: 9.37.195.0/24
    nodes:
       - hostName: "master-sm-105-ocp48-qa17"
         bmcAddress: "redfish-virtualmedia+https://9.37.131.105/redfish/v1/Systems/1" 
         bmcCredentialsName:
           name: "master-sm-105-ocp48-qa17-master-sm-105-ocp48-qa17-bmh-secret"
         bootMACAddress: "3C:EC:EF:5E:3C:0C"
         bootMode: "UEFI"
         rootDeviceHints:
           deviceName: "/dev/sda"
         cpuset: "0-1,38-39"
         nodeNetwork:
            interfaces:
            - name: eno1
              macAddress: "3C:EC:EF:5E:3C:0C"
            config:
               interfaces:
               - name: eno1
                 type: ethernet
                 state: up
                 macAddress: "3C:EC:EF:5E:3C:0C"
                 ipv4:
                   enabled: true
                   dhcp: true
                 ipv6:
                   enabled: false
