apiVersion: batch/v1
kind: Job
metadata:
  name: siteconfig-pre-master-dell-44-14dec
  namespace: clusters-sub
  generateName: pre-sync-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: ztp-site-generator
          image: mirror-registry-vranmgmt1.fyre.ibm.com:5000/redhat_emp1/ztp-site-generator:v4.10-rc.1
          command: ["/bin/bash", "pre-sync-entrypoint.sh"]
      restartPolicy: Never
  backoffLimit: 0
  ttlSecondsAfterFinished: 60


