apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: master-sm-105-ocp48-qa1
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
