---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: phoenixqa
  namespace: phoenixqa
spec:
  baseDomain: vran.ibm.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: phoenixqa
    version: v1beta1
  clusterName: phoenixqa
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: phoenixqa
  pullSecretRef:
    name: assisted-deployment-pull-secret

---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: phoenixqa
  namespace: phoenixqa
spec:
  apiVIP: 9.37.195.53
  ingressVIP: 9.37.195.54
  clusterDeploymentRef:
    name: phoenixqa
  #holdInstallation: true
  provisionRequirements:
    controlPlaneAgents: 3
  imageSetRef:
    name: "vran-ocp-v4.9.9-master-4-ocp49-2"
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwYzBzgrz+E/Lsw8FRLXTcDFYMQsiIPiiaob12McRkjSiHpCqEGH1cujJ6iOjbr1q/x30mCUsCxQ14rv9MxuYRjlydi84a9LcIwmLvYgDbHMTmVCv3XM31/LDoXRQuguuWKB4yIhSD81oigszTTgglr0gLAB0o2Ka8p1IBcXFNMwb6nIchadW9p9LtYA76yIoWdRNp8h9M4JdgnvtzkANeuKwdt7n58yNhD/aVs9L8jPvFCSVB3IfRI9LudtO8DQ7CSfdkc4LthREGAyfe+1Mp5TD7evk/c4p4LunWMZK7dE8YGxIljlaT7Tam57dGSlpnwhyf4KSd4h4xEL/InkEL"

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: phoenixqa
  namespace: phoenixqa
spec:
  clusterName: phoenixqa
  clusterNamespace: phoenixqa
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true

---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: phoenixqa
  namespace: phoenixqa
  
spec:
  clusterRef:
    name: phoenixqa
    namespace: phoenixqa
  # agentLabelSelector:
  #   matchLabels:
  #     cluster-name: phoenixqa
  pullSecretRef:
    name: assisted-deployment-pull-secret
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwYzBzgrz+E/Lsw8FRLXTcDFYMQsiIPiiaob12McRkjSiHpCqEGH1cujJ6iOjbr1q/x30mCUsCxQ14rv9MxuYRjlydi84a9LcIwmLvYgDbHMTmVCv3XM31/LDoXRQuguuWKB4yIhSD81oigszTTgglr0gLAB0o2Ka8p1IBcXFNMwb6nIchadW9p9LtYA76yIoWdRNp8h9M4JdgnvtzkANeuKwdt7n58yNhD/aVs9L8jPvFCSVB3IfRI9LudtO8DQ7CSfdkc4LthREGAyfe+1Mp5TD7evk/c4p4LunWMZK7dE8YGxIljlaT7Tam57dGSlpnwhyf4KSd4h4xEL/InkEL"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-80-std"
  namespace: phoenixqa
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.80/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa-master-dell-80-std-bmh-secret
  bootMACAddress: E4:43:4B:F0:E3:00
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-81-std"
  namespace: phoenixqa
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.81/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa-master-dell-81-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:01:10
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-82-std"
  namespace: phoenixqa
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.82/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa-master-dell-82-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:A4:E0
  automatedCleaningMode: disabled
  online: true
---
