---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: phoenixqa4
  namespace: phoenixqa4
spec:
  baseDomain: vran.ibm.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: phoenixqa4
    version: v1beta1
  clusterName: phoenixqa4
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: phoenixqa4
  pullSecretRef:
    name: assisted-deployment-pull-secret

---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: phoenixqa4
  namespace: phoenixqa4
spec:
  apiVIP: 9.37.195.53
  ingressVIP: 9.37.195.54
  clusterDeploymentRef:
    name: phoenixqa4
  #holdInstallation: true
  provisionRequirements:
    controlPlaneAgents: 3
  imageSetRef:
    name: "vran-ocp-v4.9.9-master-4-ocp49-2"
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCb30F285dDTq72HIbq+nbb2lh7MEzW5hGqDcZzJv/pAThWVxOxQrX9wmxOHVk8Rt4thENjVXehlSAAuFLhKbvPAtv3hv/XCb4Je2IUR9dOL7PTo2/46o2/eclxW8OsLdJ92QgZXZPeY1jqdj3iP43+QYUdsByEOglePT3uamstxjcKzgbgbmHq2M9Yn0+pwn2t0m1P/f4sOXOBAhfgNAC2yxCvPXnkUwReMLaBXXFIral6VW2NhF25cgEsMOhBOY8SSXpilPXXTFVaToV+vnkcVbel3kbVq9Ni6j/gnAnCh00qLDYGNFZeYNbpUfVSkzCeDYHfERjhA51314P0HZMf"

---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: phoenixqa4
  namespace: phoenixqa4
spec:
  clusterName: phoenixqa4
  clusterNamespace: phoenixqa4
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true

---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: phoenixqa4
  namespace: phoenixqa4
  
spec:
  clusterRef:
    name: phoenixqa4
    namespace: phoenixqa4
  # agentLabelSelector:
  #   matchLabels:
  #     cluster-name: phoenixqa4
  pullSecretRef:
    name: assisted-deployment-pull-secret
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCb30F285dDTq72HIbq+nbb2lh7MEzW5hGqDcZzJv/pAThWVxOxQrX9wmxOHVk8Rt4thENjVXehlSAAuFLhKbvPAtv3hv/XCb4Je2IUR9dOL7PTo2/46o2/eclxW8OsLdJ92QgZXZPeY1jqdj3iP43+QYUdsByEOglePT3uamstxjcKzgbgbmHq2M9Yn0+pwn2t0m1P/f4sOXOBAhfgNAC2yxCvPXnkUwReMLaBXXFIral6VW2NhF25cgEsMOhBOY8SSXpilPXXTFVaToV+vnkcVbel3kbVq9Ni6j/gnAnCh00qLDYGNFZeYNbpUfVSkzCeDYHfERjhA51314P0HZMf"
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-80-std"
  namespace: phoenixqa4
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa4"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.80/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa4-master-dell-80-std-bmh-secret
  bootMACAddress: E4:43:4B:F0:E3:00
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-81-std"
  namespace: phoenixqa4
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa4"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.81/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa4-master-dell-81-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:01:10
  automatedCleaningMode: disabled
  online: true
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "master-dell-82-std"
  namespace: phoenixqa4
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "phoenixqa4"
spec:
  bootMode: "UEFI"
  bmc:
    address: "idrac-virtualmedia+https://9.37.131.82/redfish/v1/Systems/System.Embedded.1" 
    disableCertificateVerification: true
    credentialsName: phoenixqa4-master-dell-82-std-bmh-secret
  bootMACAddress: E4:43:4B:F1:A4:E0
  automatedCleaningMode: disabled
  online: true
---
