---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./du-01  

resources:
  - 40-vcu-cluster-delhi-dell-du.yaml  
  - 50-vcu-cluster-delhi-dell-du-00-pre.yaml
  - 60-vcu-cluster-delhi-dell-du-01-post.yaml  
  - 70-vcu-cluster-delhi-dell-du-02-configs.yaml
